/**
 * E2E — 60-question no-repeat + rotation audit for the /learn quiz (S3 / S3.1).
 *
 * Validates the finding (2026-07-09) that within ONE session the quiz never
 * repeats a question and rotates across all six skills. It walks a single live
 * session (dev-seeded 171-item bank), bucketing each served question under its
 * `data-skill`, until EVERY skill has at least 10 questions (target 60 = 10×6).
 * The sequence does not matter — we assert the SET is unique, not its order.
 *
 * PASS: the 60 collected questions (10 per skill) are all distinct by stem text.
 * On completion it writes a human-readable Markdown report to
 * `frontend/scripts/quiz-no-repeat-60-report.md` for manual validation.
 *
 * If a duplicate is found the test FAILS and the report's summary flags it (the
 * offending stem + the two positions), so a root-cause follow-up has the evidence.
 *
 * Pure T1 (seeded browser engine, no backend/auth/LLM). Run against a running
 * bypass-auth dev server:
 *   CI=1 BASE_URL=http://localhost:3000 ./node_modules/.bin/playwright test \
 *     --project=learn-e2e e2e/learn/quiz-no-repeat-60.spec.ts --reporter=list
 */

import { test, expect, type Page } from "@playwright/test";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

/** 10 questions per skill; 6 skills → 60. */
const PER_SKILL = 10;
const TARGET_SKILLS = ["s-punc", "s-gram", "s-sent", "s-rhet", "s-org", "s-style"];
/** Safety cap: even rotation reaches 60 in ~60 items; bound the walk generously. */
const MAX_WALK = 120;

const SKILL_LABEL: Record<string, string> = {
  "s-punc": "Punctuation",
  "s-gram": "Grammar & Usage",
  "s-sent": "Sentence Structure",
  "s-rhet": "Rhetorical Skills",
  "s-org": "Organization",
  "s-style": "Style",
};

interface Served {
  order: number; // 1-based position in the whole walk
  skill: string;
  stem: string;
  choices: { letter: string; label: string }[];
}

/**
 * The QUESTION identity for dedup. NOT the stem alone: bank passages (ADR-0021)
 * are shared across several sibling questions — the UI renders the full passage
 * (`context_html`) plus the per-question prompt (`stem_md`), so two DIFFERENT
 * questions on the same passage share most of their visible text. Keying on
 * stem+choices distinguishes them (each question has a distinct prompt line AND a
 * distinct choice set), matching `question_id` uniqueness without reading the DOM's
 * internal id. This is the fix for the passage-level false-positive in the first run.
 */
function identity(item: Served): string {
  const choiceKey = item.choices.map((c) => `${c.letter}:${c.label}`).join("|");
  return `${item.stem}∥${choiceKey}`;
}

/** Read the currently-served item: skill, stem, and its A–D choice labels. */
async function readItem(page: Page): Promise<Served | null> {
  const skillEl = page.locator("[data-skill]").first();
  if ((await skillEl.count()) === 0) return null;
  const skill = (await skillEl.getAttribute("data-skill")) ?? "";
  const stem = (await page.locator("[data-testid='quiz-context']").first().textContent())?.trim() ?? "";
  const choices = await page.locator("[data-testid^='choice-']").evaluateAll((els) =>
    els
      .map((e) => ({
        letter: (e.getAttribute("data-testid") ?? "").replace("choice-", ""),
        label: (e.querySelector("span:last-child")?.textContent ?? e.textContent ?? "").trim(),
      }))
      .filter((c) => c.letter.length === 1),
  );
  return { order: 0, skill, stem, choices };
}

/** Answer the current item (A → Submit) and advance past feedback to the next. */
async function answerAndAdvance(page: Page): Promise<void> {
  await page.locator("[data-testid='choice-A']").click();
  await page.locator("[data-testid='quiz-submit']").click();
  await expect(page.locator("[data-testid='feedback-banner']")).toBeVisible({ timeout: 10_000 });
  await page.locator("[data-testid='quiz-next']").click();
  await page.locator("[data-skill]").first().waitFor({ timeout: 10_000 });
}

function buildReport(
  perSkill: Map<string, Served[]>,
  duplicates: { stem: string; first: number; second: number }[],
  totalWalked: number,
): string {
  const lines: string[] = [];
  const all: Served[] = [];
  for (const s of TARGET_SKILLS) all.push(...(perSkill.get(s) ?? []).slice(0, PER_SKILL));
  const uniqueQuestions = new Set(all.map((x) => identity(x)));
  const distinctPassages = new Set(
    all.map((x) => (x.stem.match(/^Passage [IVX]+ — [^—]+/)?.[0] ?? x.stem).trim()),
  );

  lines.push("# `/learn` quiz — 60-question no-repeat audit (S3 / S3.1)");
  lines.push("");
  lines.push(`Generated by \`e2e/learn/quiz-no-repeat-60.spec.ts\` — one live session, dev-seeded 171-item bank.`);
  lines.push("");
  lines.push("> **Question identity = prompt + choices, not passage.** ACT-English bank");
  lines.push("> items (ADR-0021) share reading passages: several DIFFERENT questions hang");
  lines.push("> off one passage, so their visible text overlaps. Uniqueness is judged on");
  lines.push("> the prompt line + answer choices (≈ `question_id`), NOT the shared passage.");
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`- Questions walked total: **${totalWalked}**`);
  lines.push(`- Collected for report: **${all.length}** (target ${PER_SKILL * TARGET_SKILLS.length} = ${PER_SKILL}×${TARGET_SKILLS.length})`);
  lines.push(`- Distinct questions (prompt+choices): **${uniqueQuestions.size} of ${all.length}**`);
  lines.push(`- Distinct passages spanned: **${distinctPassages.size}** (expected < 60 — passages are shared)`);
  lines.push(`- Duplicate questions found: **${duplicates.length}** ${duplicates.length === 0 ? "✅ (all unique)" : "❌"}`);
  lines.push("");
  lines.push("| Skill | Collected |");
  lines.push("|---|---|");
  for (const s of TARGET_SKILLS) {
    lines.push(`| ${SKILL_LABEL[s]} (\`${s}\`) | ${(perSkill.get(s) ?? []).slice(0, PER_SKILL).length} |`);
  }
  lines.push("");
  if (duplicates.length > 0) {
    lines.push("### ❌ Duplicates");
    lines.push("");
    for (const d of duplicates) {
      lines.push(`- Positions ${d.first} & ${d.second}: \`${d.stem.slice(0, 90)}\``);
    }
    lines.push("");
  }
  lines.push("---");
  lines.push("");
  lines.push("## All 60 questions (grouped by skill)");
  lines.push("");
  let n = 0;
  for (const s of TARGET_SKILLS) {
    lines.push(`### ${SKILL_LABEL[s]} (\`${s}\`)`);
    lines.push("");
    for (const item of (perSkill.get(s) ?? []).slice(0, PER_SKILL)) {
      n += 1;
      // Split the visible stem into the shared passage header and the per-question
      // prompt so the report is readable and the passage-sharing is obvious. The
      // prompt is the last sentence-like clause; fall back to the whole stem.
      const m = item.stem.match(/^(Passage [IVX]+ — .+?)\s*—?\s*((?:Which|What|The best|Choose|Where|How)\b.*)$/);
      const passage = m ? m[1] : "";
      const prompt = m ? m[2] : item.stem;
      lines.push(`**${n}.** _(served #${item.order})_ **${prompt}**`);
      if (passage) lines.push(`   > ${passage.slice(0, 140)}${passage.length > 140 ? "…" : ""}`);
      for (const c of item.choices) lines.push(`   - ${c.letter}. ${c.label}`);
      lines.push("");
    }
  }
  return lines.join("\n");
}

test("60 questions (10 per skill) in one session are all unique", async ({ page }) => {
  test.setTimeout(180_000); // a 60+ item walk needs headroom
  await page.goto("/learn/quiz", { waitUntil: "networkidle" });

  const first = await readItem(page);
  test.skip(first == null, "Skipped: quiz item not rendered (auth/env).");

  const perSkill = new Map<string, Served[]>(TARGET_SKILLS.map((s) => [s, []]));
  const seen = new Map<string, number>(); // question identity → first position
  const duplicates: { stem: string; first: number; second: number }[] = [];
  let walked = 0;

  const record = (item: Served) => {
    walked += 1;
    item.order = walked;
    const bucket = perSkill.get(item.skill);
    if (bucket && bucket.length < PER_SKILL) bucket.push(item);
    // Dedup across the whole walk (not just the kept 10) — a repeat anywhere is a
    // bug. Identity is stem+choices, so passage-siblings (same passage, different
    // question) are NOT counted as duplicates (see `identity`).
    const key = identity(item);
    if (seen.has(key)) {
      duplicates.push({ stem: item.stem, first: seen.get(key)!, second: walked });
    } else {
      seen.set(key, walked);
    }
  };

  const done = () => TARGET_SKILLS.every((s) => (perSkill.get(s)?.length ?? 0) >= PER_SKILL);

  record(first!);
  while (!done() && walked < MAX_WALK) {
    await answerAndAdvance(page);
    const item = await readItem(page);
    if (item == null) break;
    record(item);
  }

  const report = buildReport(perSkill, duplicates, walked);
  const out = join(process.cwd(), "scripts", "quiz-no-repeat-60-report.md");
  writeFileSync(out, report, "utf8");
  console.log(`\nReport written: ${out}`);
  console.log(`walked=${walked} duplicates=${duplicates.length} perSkill=` +
    TARGET_SKILLS.map((s) => `${s}:${perSkill.get(s)?.length ?? 0}`).join(" "));

  // Assertions: every skill reached 10, and the collected 60 are all unique.
  for (const s of TARGET_SKILLS) {
    expect(perSkill.get(s)?.length ?? 0, `skill ${s} did not reach ${PER_SKILL} within ${MAX_WALK} items`).toBe(PER_SKILL);
  }
  expect(
    duplicates.length,
    `duplicate question(s) within the session: ${duplicates.map((d) => `[${d.first}=${d.second}] ${d.stem.slice(0, 60)}`).join(" ; ")}`,
  ).toBe(0);
});
