"""FR-B2/B3 — the generated Python plane is parity-pinned to the canonical JSON.

``components/subject_coach_bank_hints.py`` is GENERATED by
``scripts/emit_hint_bank.py``; these tests pin it row-for-row to
``docs/plan/coach-bank-hints.seed.json`` so a hand edit or a stale
regeneration on either side fails in CI (the FR-B2 drift pin — the successor
of the retired two-plane parity suite, now with a machine-generated module on
each side of one canonical source).
"""

from __future__ import annotations

import json
from pathlib import Path

from components.subject_coach_bank_hints import BANK_RUNGS

_REPO = Path(__file__).resolve().parent.parent.parent
_SEED_JSON = _REPO / "docs" / "plan" / "coach-bank-hints.seed.json"


def _corpus_rows() -> list[dict]:
    rows = json.loads(_SEED_JSON.read_text(encoding="utf-8"))["rows"]
    return sorted(
        rows, key=lambda r: (r["question_id"], r.get("choice_letter") or "", r["rung"])
    )


def test_bank_rungs_match_the_seed_row_for_row() -> None:
    rows = _corpus_rows()
    assert len(BANK_RUNGS) == len(rows)
    for rung, row in zip(BANK_RUNGS, rows, strict=True):
        assert rung.question_id == row["question_id"]
        assert rung.rung == row["rung"]
        assert rung.body_md == row["body_md"]
        assert rung.reviewed is True
        assert rung.choice_letter == row.get("choice_letter")


def test_authored_by_carries_the_generated_by_stamp_verbatim() -> None:
    """FR-B3: provenance is identical on both serving planes."""
    stamps = {row["id"]: row["generated_by"] for row in _corpus_rows()}
    assert all("@" in s for s in stamps.values())
    by_key = {
        (row["question_id"], row.get("choice_letter"), row["rung"]): row["generated_by"]
        for row in _corpus_rows()
    }
    for rung in BANK_RUNGS:
        assert (
            rung.authored_by
            == by_key[(rung.question_id, rung.choice_letter, rung.rung)]
        )


def test_rungs_are_sorted_and_unique_per_question() -> None:
    keys = [(r.question_id, r.choice_letter, r.rung) for r in BANK_RUNGS]
    assert keys == sorted(keys, key=lambda k: (k[0], k[1] or "", k[2]))
    assert len(keys) == len(set(keys)), "duplicate (question_id, choice_letter, rung)"
