/**
 * Regenerate `frontend/lib/wire/__python_schema_baseline__.json` from the
 * Python wire models -- this is the ground truth the TS schemas mirror.
 *
 * The Python exporter (`python -m agent_ui_adapter.wire.export_openapi`)
 * prints OpenAPI 3.1 YAML to stdout. We extract `components.schemas` and
 * subset it to the wire shapes the TS side reproduces. The Drift CI job
 * (S3.11.1) re-runs this snapshot in dry-run mode and fails the build if
 * any field, type, or required-set has changed.
 *
 * Usage: `npm run wire-schema-snapshot` from `frontend/`.
 *
 * NOTE: this script intentionally lives under `frontend/scripts/` (not
 * `lib/`) so it never participates in the dependency-rule enforcement test
 * (Pattern 7) -- the wire ring stays Zod-only in production code.
 */

import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import path from "node:path";
import * as YAML from "js-yaml";

interface OpenAPIDoc {
  components?: { schemas?: Record<string, unknown> };
}

const REPO_ROOT = path.resolve(import.meta.dirname, "..", "..");
const BASELINE_PATH = path.resolve(
  import.meta.dirname,
  "..",
  "lib",
  "wire",
  "__python_schema_baseline__.json",
);

// Schemas we mirror in TS. If you add a Pydantic model under
// `agent_ui_adapter/wire/`, add it here and bump the TS schema.
const TRACKED_MODELS = [
  // agent_protocol.py
  "ThreadCreateRequest",
  "ThreadState",
  "RunCreateRequest",
  "RunStateView",
  "HealthResponse",
  // domain_events.py
  "LLMTokenEmitted",
  "LLMMessageStarted",
  "LLMMessageEnded",
  "ToolCallStarted",
  "ToolCallEnded",
  "ToolResultReceived",
  "RunStartedDomain",
  "RunFinishedDomain",
  "StateMutated",
  // ag_ui_events.py
  "RunStarted",
  "RunFinished",
  "RunError",
  "StepStarted",
  "StepFinished",
  "TextMessageStart",
  "TextMessageContent",
  "TextMessageEnd",
  "ToolCallStart",
  "ToolCallArgs",
  "ToolCallEnd",
  "ToolResult",
  "StateSnapshot",
  "StateDelta",
  "MessagesSnapshot",
  "Raw",
  "Custom",
];

function exportOpenAPI(): OpenAPIDoc {
  const yaml = execSync("python -m agent_ui_adapter.wire.export_openapi", {
    cwd: REPO_ROOT,
    encoding: "utf8",
    maxBuffer: 16 * 1024 * 1024,
  });
  const parsed = YAML.load(yaml) as OpenAPIDoc;
  return parsed;
}

function extractTracked(doc: OpenAPIDoc): Record<string, unknown> {
  const schemas = doc.components?.schemas ?? {};
  const out: Record<string, unknown> = {};
  for (const name of TRACKED_MODELS.sort()) {
    if (!(name in schemas)) {
      throw new Error(
        `Python OpenAPI export is missing model '${name}'. ` +
          `Either remove it from TRACKED_MODELS or add the Pydantic model.`,
      );
    }
    out[name] = (schemas as Record<string, unknown>)[name];
  }
  return out;
}

function main(): void {
  const doc = exportOpenAPI();
  const tracked = extractTracked(doc);
  const baseline = {
    $comment:
      "Generated by `npm run wire-schema-snapshot`. Do NOT edit by hand. " +
      "Source of truth: agent_ui_adapter/wire/*.py. The Drift CI (S3.11.1) " +
      "fails if this file diverges from a fresh Python export.",
    pinned_agui_version: "0.1.18",
    schemas: tracked,
  };
  writeFileSync(BASELINE_PATH, JSON.stringify(baseline, null, 2) + "\n", "utf8");
  // eslint-disable-next-line no-console
  console.log(`Wrote ${BASELINE_PATH} (${Object.keys(tracked).length} schemas).`);
}

main();
