"""Measure GoalJudge vs the L2/L3 seed gold set — diagnosis only, no judge change.

docs/plans (GoalJudge-vs-seed measurement), Steps 2-4. Compares the automated
GoalJudge ``goal_met`` verdicts (harvested by harvest_l2l3_goaljudge.py) against the
human blind-adjudicated seed labels, across 6 cells:
  {full, clean} x {strict, lenient, exclude-partial}.

Reuses services/governance/goaljudge_calibration.py (confusion/precision-recall/kappa/
gate) — NOT hand-rolled. Both that module's maps are ``item_id -> goal_met`` (True =
met); the module treats "not-met" as the positive class internally, so:
  fp = judge not-met ∧ gold met   = FALSE DOWNGRADE (the off-label harm we quantify)
  fn = judge met     ∧ gold not-met = missed failure
We therefore pass natural True=met maps on both sides (no negation).

Partial mapping (seed 3-class -> binary gold goal_met):
  strict          : met <=> adjudicated == "correct"            (partial -> not-met)
  lenient         : met <=> adjudicated in {correct, partial}   (partial -> met)
  exclude-partial : drop partial rows; met <=> "correct"

Clean subset: drop the 15 harness-bug items (8 access-failures + 7 off-topic routing)
from the rater-2 root-cause notes — environment defects, not reasoning the judge
should be measured on.

Outputs cache/goaljudge_eval/model_ab_l2l3_goaljudge_vs_seed.{json,md}.
"""

from __future__ import annotations

import json
from pathlib import Path

from services.governance.goaljudge_calibration import (
    confusion_counts,
    evaluate_section_2_8_gates,
    expected_calibration_error,
    judge_gold_kappa,
    precision_recall_fd,
)

AGENT_ROOT = Path(__file__).resolve().parent.parent
ANSWER_DIR = AGENT_ROOT / "cache" / "model_ab_answer"
# The combined full-seed verdict file (52 base cascade + 45 growth = 97 items),
# canonical now that the seed is 97 rows (the 5th growth arm glm-5.1 was added
# 2026-06-28; run_growth_goaljudge.py resume-mode judged only the 9 new items and
# this file was rebuilt by merging base + growth). The base-only file
# (l2l3_goaljudge_verdicts.json) covered just cases 07-15 and no longer aligns.
GJ_VERDICTS = ANSWER_DIR / "l2l3_full97_goaljudge_verdicts.json"
SEED = AGENT_ROOT / "cache" / "goaljudge_eval" / "model_ab_l2l3_goldset_seed.json"
OUT_JSON = (
    AGENT_ROOT / "cache" / "goaljudge_eval" / "model_ab_l2l3_goaljudge_vs_seed.json"
)
OUT_MD = AGENT_ROOT / "cache" / "goaljudge_eval" / "model_ab_l2l3_goaljudge_vs_seed.md"

# The 15 harness-bug items (rater-2 root-cause notes): item_id prefixes (12 hex).
ACCESS_FAILURE = [
    "f623fe11",
    "24ee3d4c",
    "18f180fd",
    "6d386b69",
    "6929d618",
    "b205d8bb",
    "d0460cfd",
    "0d11f2f8",
]
OFF_TOPIC = [
    "9c18000e",
    "17340957",
    "586630b5",
    "c6e723be",
    "2ba4b3f5",
    "f6245521",
    "3d6637de",
]
HARNESS_BUG_PREFIXES = set(ACCESS_FAILURE + OFF_TOPIC)

# Growth wave (cases 16-24): answers cut at the 500-char harvest clip before their
# load-bearing conclusion. GoalJudge correctly marks a cut-off answer not-met while
# the human read through the truncation per the rater protocol — a DATA-CAPTURE
# defect, not a judge error. Dropped from the CLEAN gate exactly like the base-wave
# env-defect items (precedent: 70ff3369, docs/adr/0003). The list is keyed on the
# truncation criterion (answer >=498 chars, cut mid-conclusion), NOT on whether a
# row helps or hurts the gate — no outcome-driven cherry-picking (7 of the original
# 18 were the false-downgrades; all 18 are excluded uniformly). The 5 glm-5.1 entries
# (2026-06-28, 5th growth arm) are the SAME rule applied to the new arm — 2 of them
# are false-downgrades, 3 are not; all 5 excluded uniformly. Generated by the
# truncation check in scripts/run_growth_goaljudge.py's source answers; kept as full
# 32-hex ids (not 8-char prefixes) so each maps to exactly one (arm, case).
TRUNCATED_AT_SOURCE: dict[str, str] = {
    "94f32e5d6d575c88b827c1b68724fa33": "opus / GEN-L2-dependency-resolve-20",
    "6e6f4932db1a573b8b04b09d66d81949": "haiku / GEN-L2-multi-source-synthesis-19",
    "4ddfb3c6946d56dd9370336f39ac7571": "opus / GEN-L2-pipeline-transform-18",
    "2d0a2430af035065ab348ac55430206a": "flash / GEN-L2-pipeline-transform-18",
    "8610c4f66edd5e6ba7f990b6182b1b21": "haiku / GEN-L2-verify-and-fix-22",
    "341cc0f42cbb5e969fdee3591372f52f": "opus / GEN-L2-verify-and-fix-22",
    "49c36a6ef2895a0f897179b6c016f79b": "flash / GEN-L2-verify-and-fix-22",
    "d4bb13ee90805587ae63163ff84914b3": "pro / GEN-L2-verify-and-fix-22",
    "f7b0cd0ba3d3573dbdd54a6fffdaf19c": "opus / GEN-L3-constraint-solve-21",
    "df36e15fb7bc5a38bb042e8c02a079c5": "flash / GEN-L3-constraint-solve-21",
    "6b72c824c76e5cdfb3df5c078b46430f": "haiku / GEN-L3-iterative-refine-24",
    "4b74402ef0595eb99d48cd0ec1fe4ba8": "opus / GEN-L3-iterative-refine-24",
    "24d10e92a11c54919dec288a5ef19045": "flash / GEN-L3-iterative-refine-24",
    "03d57a681eb757f491a4e790d0c59891": "pro / GEN-L3-iterative-refine-24",
    "35604d1f1f545082bfe4c7b2bff66898": "haiku / GEN-L3-multi-hop-synthesis-23",
    "5941e095d3a85de3aef37012853267f2": "opus / GEN-L3-multi-hop-synthesis-23",
    "b60b624fdfa75e2f8fbffb57359cc699": "flash / GEN-L3-multi-hop-synthesis-23",
    "58865d01376354fa8e519bc50106ab16": "pro / GEN-L3-multi-hop-synthesis-23",
    # --- 5th growth arm (glm-5.1), added 2026-06-28 — same ans_len>=498 criterion ---
    "1ab7b668670a5d7a9323ab79ebe0c414": "glm-5.1 / GEN-L2-dependency-resolve-20",
    "78b9987b859e5fb08f711816c1f0e462": "glm-5.1 / GEN-L2-multi-source-synthesis-19",
    "0c3a7424b48e5e8690900dd6d0314685": "glm-5.1 / GEN-L2-verify-and-fix-22",
    "57d7af1e7f77559bb152b1e928da07d2": "glm-5.1 / GEN-L3-iterative-refine-24",
    "ee184d671dbd58c19170a72cab39bf4a": "glm-5.1 / GEN-L3-multi-hop-synthesis-23",
}


def _gold_met(adjudicated: str, mapping: str) -> bool | None:
    """seed 3-class -> binary gold goal_met (True = met); None drops the row."""
    if mapping == "strict":
        return adjudicated == "correct"
    if mapping == "lenient":
        return adjudicated in {"correct", "partial"}
    if mapping == "exclude-partial":
        if adjudicated == "partial":
            return None
        return adjudicated == "correct"
    raise ValueError(f"unknown mapping {mapping!r}")


def _is_harness_bug(item_id: str) -> bool:
    """True for the 15 base-wave ENV defects only (access-failure / off-topic).

    Stays narrow: truncation rides ``_is_excluded_from_clean`` so the two
    exclusion categories remain independently auditable."""
    return item_id[:8] in {p[:8] for p in HARNESS_BUG_PREFIXES}


def _is_truncated_at_source(item_id: str) -> bool:
    """True for a growth answer cut at the 500-char harvest clip (data defect)."""
    return item_id in TRUNCATED_AT_SOURCE


def _is_excluded_from_clean(item_id: str) -> bool:
    """The full CLEAN-gate exclusion: env defect OR truncated-at-source.

    The validator's ``--clean`` flag drops exactly these — both are data-capture
    defects the judge should not be scored on (not judge errors)."""
    return _is_harness_bug(item_id) or _is_truncated_at_source(item_id)


def _cell_metrics(
    items: list[str],
    judge_met: dict[str, bool],
    adjudicated: dict[str, str],
    criteria: dict[str, float | None],
    mapping: str,
) -> dict:
    """One {subset x mapping} cell."""
    judge: dict[str, bool] = {}
    gold: dict[str, bool] = {}
    for i in items:
        g = _gold_met(adjudicated[i], mapping)
        if g is None:  # exclude-partial drops partial rows
            continue
        judge[i] = judge_met[i]
        gold[i] = g

    if not judge:
        return {"n": 0, "note": "no rows after mapping"}

    counts = confusion_counts(judge, gold)
    prf = precision_recall_fd(counts)
    kappa = judge_gold_kappa(judge, gold)

    # ECE on the criteria_met confidence proxy (diagnostic only). Needs a proxy in
    # [0,1] for every graded item; skip rows whose criteria_met is missing.
    conf = {
        i: float(criteria[i])
        for i in judge
        if criteria.get(i) is not None and 0.0 <= float(criteria[i]) <= 1.0
    }
    ece = (
        expected_calibration_error(
            {i: conf[i] for i in conf}, {i: gold[i] for i in conf}
        )
        if conf
        else None
    )

    return {
        "n": len(judge),
        "tp_judge_notmet_gold_notmet": counts.tp,
        "fp_FALSE_DOWNGRADE": counts.fp,
        "fn_missed_failure": counts.fn,
        "tn": counts.tn,
        "precision": prf.precision,
        "recall": prf.recall,
        "false_downgrade_rate": prf.false_downgrade_rate,
        "kappa": kappa,
        "ece_criteria_met_proxy": ece,
    }


def measure() -> dict:
    gj = json.loads(GJ_VERDICTS.read_text())
    seed = json.loads(SEED.read_text())
    manifest = seed["manifest"]
    rows = {r["item_id"]: r for r in seed["rows"]}

    judge_met = {i: gj[i]["goal_met"] for i in gj}
    adjudicated = {i: rows[i]["adjudicated"] for i in gj}
    criteria = {i: gj[i].get("criteria_met") for i in gj}

    all_items = list(gj)
    clean_items = [i for i in all_items if not _is_harness_bug(i)]

    cells: dict[str, dict] = {}
    for subset_name, items in (("full", all_items), ("clean", clean_items)):
        for mapping in ("strict", "lenient", "exclude-partial"):
            cells[f"{subset_name}/{mapping}"] = _cell_metrics(
                items, judge_met, adjudicated, criteria, mapping
            )

    # Formal gate (uses the strict/full metrics + the provisional manifest). The
    # seed is provisional -> expect REFUSE_PROVISIONAL (a provisional seed cannot
    # certify the judge). We report this alongside the raw diagnostic metrics.
    strict_full = cells["full/strict"]
    gate = evaluate_section_2_8_gates(
        precision=strict_full.get("precision"),
        recall=strict_full.get("recall"),
        false_downgrade_rate=strict_full.get("false_downgrade_rate"),
        kappa=strict_full.get("kappa", float("nan")),
        flip=None,
        manifest=manifest,
    )

    # Per-arm confusion (strict/full): which models' answers the judge mis-judges.
    per_arm: dict[str, dict] = {}
    for i in all_items:
        arm = gj[i]["arm"]
        g = _gold_met(adjudicated[i], "strict")
        j = judge_met[i]
        d = per_arm.setdefault(arm, {"tp": 0, "fp": 0, "fn": 0, "tn": 0})
        if not j and not g:
            d["tp"] += 1
        elif not j and g:
            d["fp"] += 1  # false downgrade
        elif j and not g:
            d["fn"] += 1
        else:
            d["tn"] += 1

    # Disagreement table (strict/full): judge_met != gold_met.
    disagreements = []
    for i in all_items:
        g = _gold_met(adjudicated[i], "strict")
        j = judge_met[i]
        if j != g:
            disagreements.append(
                {
                    "item_id": i,
                    "case": gj[i]["case"],
                    "arm": gj[i]["arm"],
                    "goaljudge_goal_met": j,
                    "seed_adjudicated": adjudicated[i],
                    "gold_met_strict": g,
                    "kind": "false_downgrade" if (not j and g) else "missed_failure",
                    "goaljudge_rationale": gj[i].get("rationale", "")[:240],
                }
            )

    return {
        "manifest_ref": {
            "name": manifest["name"],
            "provisional": manifest["provisional"],
            "n_items": len(all_items),
            "seed_alpha_3class": manifest["agreement"]["krippendorff_alpha_3class"],
        },
        "cells": cells,
        "formal_gate": {"verdict": gate.verdict, "gates": dict(gate.gates)},
        "per_arm_confusion_strict_full": per_arm,
        "disagreements_strict_full": disagreements,
    }


def _fmt(x) -> str:
    if x is None:
        return "—"
    if isinstance(x, float):
        return f"{x:.3f}"
    return str(x)


def to_markdown(result: dict) -> str:
    m = result["manifest_ref"]
    L = []
    L.append("# GoalJudge vs L2/L3 Seed Gold Set — Measurement\n")
    L.append(
        f"> **Diagnosis only, no judge code changed.** Gold = the PROVISIONAL "
        f"blind-adjudicated seed (`{m['name']}`, n={m['n_items']}, 2-rater "
        f"α={m['seed_alpha_3class']}). Positive class = *not-met* (the downgrade "
        f"signal): **fp = false downgrade** (judge fails a gold-met answer — the "
        f"off-label harm), fn = missed failure.\n"
    )
    L.append(
        "> Partial mapping: **strict** partial→not-met · **lenient** partial→met · "
        "**exclude-partial** drops partials. **clean** subset removes the 15 "
        "harness-bug items (8 access-failure + 7 off-topic routing).\n"
    )

    L.append("\n## Metrics (6 cells)\n")
    L.append(
        "| cell | n | precision | recall | false-downgrade | κ(judge↔gold) | fp | fn |"
    )
    L.append("|---|--:|--:|--:|--:|--:|--:|--:|")
    for name, c in result["cells"].items():
        if c.get("n", 0) == 0:
            L.append(f"| {name} | 0 | — | — | — | — | — | — |")
            continue
        L.append(
            f"| {name} | {c['n']} | {_fmt(c['precision'])} | {_fmt(c['recall'])} | "
            f"{_fmt(c['false_downgrade_rate'])} | {_fmt(c['kappa'])} | "
            f"{c['fp_FALSE_DOWNGRADE']} | {c['fn_missed_failure']} |"
        )

    g = result["formal_gate"]
    L.append(f"\n## Formal §2.8 gate verdict: **{g['verdict']}**")
    L.append(
        "\nThe §2.8 evaluator refuses provisional manifests before reading a "
        "metric — `REFUSE_PROVISIONAL` is expected and correct: a provisional "
        "seed cannot certify the judge. The raw metrics above are the "
        "diagnostic finding.\n"
    )

    L.append("\n## Per-arm confusion (strict / full)\n")
    L.append("| arm | tp | fp (false downgrade) | fn | tn |")
    L.append("|---|--:|--:|--:|--:|")
    for arm, d in sorted(result["per_arm_confusion_strict_full"].items()):
        L.append(f"| {arm} | {d['tp']} | {d['fp']} | {d['fn']} | {d['tn']} |")

    L.append("\n## Disagreements (strict / full) — where GoalJudge ≠ the seed\n")
    L.append("| item | case | arm | judge goal_met | seed | kind | rationale |")
    L.append("|---|---|---|:--:|:--:|---|---|")
    for d in result["disagreements_strict_full"]:
        rat = d["goaljudge_rationale"].replace("\n", " ").replace("|", "/")
        L.append(
            f"| {d['item_id'][:8]} | {d['case']} | {d['arm']} | "
            f"{d['goaljudge_goal_met']} | {d['seed_adjudicated']} | {d['kind']} | "
            f"{rat} |"
        )
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    result = measure()
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(result, indent=2) + "\n")
    OUT_MD.write_text(to_markdown(result))
    print(f"wrote {OUT_JSON}")
    print(f"wrote {OUT_MD}")
    sf = result["cells"]["full/strict"]
    sc = result["cells"]["clean/strict"]
    print(
        f"\nstrict/full : precision={_fmt(sf['precision'])} "
        f"recall={_fmt(sf['recall'])} FD={_fmt(sf['false_downgrade_rate'])} "
        f"κ={_fmt(sf['kappa'])}  (fp={sf['fp_FALSE_DOWNGRADE']} fn={sf['fn_missed_failure']})"
    )
    print(
        f"strict/clean: precision={_fmt(sc['precision'])} "
        f"recall={_fmt(sc['recall'])} FD={_fmt(sc['false_downgrade_rate'])} "
        f"κ={_fmt(sc['kappa'])}  (fp={sc['fp_FALSE_DOWNGRADE']} fn={sc['fn_missed_failure']})"
    )
    print(f"formal gate: {result['formal_gate']['verdict']}")
