/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agent/runs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open an SSE stream of AG-UI events for a run */
        post: operations["streamRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get run state */
        get: operations["getRun"];
        put?: never;
        post?: never;
        /** Cancel a run */
        delete: operations["cancelRun"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List threads */
        get: operations["listThreads"];
        put?: never;
        /** Create a thread */
        post: operations["createThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a thread */
        get: operations["getThread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BaseEvent
         * @description Common header for every AG-UI event.
         */
        BaseEvent: {
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            type: components["schemas"]["EventType"];
            $defs: {
                /**
                 * EventType
                 * @description The 17 AG-UI event-type discriminator strings.
                 * @enum {string}
                 */
                EventType: "RUN_STARTED" | "RUN_FINISHED" | "RUN_ERROR" | "STEP_STARTED" | "STEP_FINISHED" | "TEXT_MESSAGE_START" | "TEXT_MESSAGE_CONTENT" | "TEXT_MESSAGE_END" | "TOOL_CALL_START" | "TOOL_CALL_ARGS" | "TOOL_CALL_END" | "TOOL_RESULT" | "STATE_SNAPSHOT" | "STATE_DELTA" | "MESSAGES_SNAPSHOT" | "RAW" | "CUSTOM";
            };
        };
        /** Custom */
        Custom: {
            /** Name */
            name: string;
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default CUSTOM
             * @constant
             */
            type: "CUSTOM";
            /** Value */
            value: {
                [key: string]: unknown;
            };
        };
        /**
         * DomainEventBase
         * @description Common header for every internal domain event.
         */
        DomainEventBase: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * EventType
         * @description The 17 AG-UI event-type discriminator strings.
         * @enum {string}
         */
        EventType: "RUN_STARTED" | "RUN_FINISHED" | "RUN_ERROR" | "STEP_STARTED" | "STEP_FINISHED" | "TEXT_MESSAGE_START" | "TEXT_MESSAGE_CONTENT" | "TEXT_MESSAGE_END" | "TOOL_CALL_START" | "TOOL_CALL_ARGS" | "TOOL_CALL_END" | "TOOL_RESULT" | "STATE_SNAPSHOT" | "STATE_DELTA" | "MESSAGES_SNAPSHOT" | "RAW" | "CUSTOM";
        /**
         * HealthResponse
         * @description Response body of ``GET /healthz``.
         */
        HealthResponse: {
            /** Adapter Version */
            adapter_version: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** LLMMessageEnded */
        LLMMessageEnded: {
            /** Message Id */
            message_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Trace Id */
            trace_id: string;
        };
        /** LLMMessageStarted */
        LLMMessageStarted: {
            /** Message Id */
            message_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Trace Id */
            trace_id: string;
        };
        /** LLMTokenEmitted */
        LLMTokenEmitted: {
            /** Delta */
            delta: string;
            /** Message Id */
            message_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Trace Id */
            trace_id: string;
        };
        /** MessagesSnapshot */
        MessagesSnapshot: {
            /** Messages */
            messages: {
                [key: string]: unknown;
            }[];
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default MESSAGES_SNAPSHOT
             * @constant
             */
            type: "MESSAGES_SNAPSHOT";
        };
        /** Raw */
        Raw: {
            /** Event */
            event: string;
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Source
             * @default null
             */
            source: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default RAW
             * @constant
             */
            type: "RAW";
        };
        /**
         * RunCreateRequest
         * @description Body of ``POST /agent/runs/stream`` and ``POST /agent/runs``.
         */
        RunCreateRequest: {
            /**
             * Agent Id
             * @default null
             */
            agent_id: string | null;
            /** Input */
            input: {
                [key: string]: unknown;
            };
            /** Thread Id */
            thread_id: string;
        };
        /** RunError */
        RunError: {
            /**
             * Code
             * @default null
             */
            code: string | null;
            /** Message */
            message: string;
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /** Run Id */
            run_id: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default RUN_ERROR
             * @constant
             */
            type: "RUN_ERROR";
        };
        /** RunFinished */
        RunFinished: {
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /** Run Id */
            run_id: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default RUN_FINISHED
             * @constant
             */
            type: "RUN_FINISHED";
        };
        /** RunFinishedDomain */
        RunFinishedDomain: {
            /**
             * Error
             * @default null
             */
            error: string | null;
            /** Run Id */
            run_id: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Trace Id */
            trace_id: string;
        };
        /** RunStarted */
        RunStarted: {
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /** Run Id */
            run_id: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default RUN_STARTED
             * @constant
             */
            type: "RUN_STARTED";
        };
        /** RunStartedDomain */
        RunStartedDomain: {
            /** Run Id */
            run_id: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * RunStateView
         * @description Response body of ``GET /agent/runs/{run_id}``.
         */
        RunStateView: {
            /** Completed At */
            completed_at: string | null;
            /** Run Id */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "completed" | "cancelled" | "errored";
            /** Thread Id */
            thread_id: string;
        };
        /** StateDelta */
        StateDelta: {
            /** Delta */
            delta: {
                [key: string]: unknown;
            }[];
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default STATE_DELTA
             * @constant
             */
            type: "STATE_DELTA";
        };
        /** StateMutated */
        StateMutated: {
            /**
             * Delta
             * @default null
             */
            delta: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Snapshot
             * @default null
             */
            snapshot: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Trace Id */
            trace_id: string;
        };
        /** StateSnapshot */
        StateSnapshot: {
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /** Snapshot */
            snapshot: {
                [key: string]: unknown;
            };
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default STATE_SNAPSHOT
             * @constant
             */
            type: "STATE_SNAPSHOT";
        };
        /** StepFinished */
        StepFinished: {
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /** Step Name */
            step_name: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default STEP_FINISHED
             * @constant
             */
            type: "STEP_FINISHED";
        };
        /** StepStarted */
        StepStarted: {
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /** Step Name */
            step_name: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default STEP_STARTED
             * @constant
             */
            type: "STEP_STARTED";
        };
        /** TextMessageContent */
        TextMessageContent: {
            /** Delta */
            delta: string;
            /** Message Id */
            message_id: string;
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default TEXT_MESSAGE_CONTENT
             * @constant
             */
            type: "TEXT_MESSAGE_CONTENT";
        };
        /** TextMessageEnd */
        TextMessageEnd: {
            /** Message Id */
            message_id: string;
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default TEXT_MESSAGE_END
             * @constant
             */
            type: "TEXT_MESSAGE_END";
        };
        /** TextMessageStart */
        TextMessageStart: {
            /** Message Id */
            message_id: string;
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Role
             * @constant
             */
            role: "assistant";
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default TEXT_MESSAGE_START
             * @constant
             */
            type: "TEXT_MESSAGE_START";
        };
        /**
         * ThreadCreateRequest
         * @description Body of ``POST /agent/threads``.
         */
        ThreadCreateRequest: {
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** User Id */
            user_id: string;
        };
        /**
         * ThreadState
         * @description Response body of ``GET /agent/threads/{thread_id}``.
         */
        ThreadState: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Messages */
            messages?: {
                [key: string]: unknown;
            }[];
            /** Thread Id */
            thread_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** User Id */
            user_id: string;
        };
        /** ToolCallArgs */
        ToolCallArgs: {
            /** Delta */
            delta: string;
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Tool Call Id */
            tool_call_id: string;
            /**
             * Type
             * @default TOOL_CALL_ARGS
             * @constant
             */
            type: "TOOL_CALL_ARGS";
        };
        /** ToolCallEnd */
        ToolCallEnd: {
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Tool Call Id */
            tool_call_id: string;
            /**
             * Type
             * @default TOOL_CALL_END
             * @constant
             */
            type: "TOOL_CALL_END";
        };
        /** ToolCallEnded */
        ToolCallEnded: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Tool Call Id */
            tool_call_id: string;
            /** Trace Id */
            trace_id: string;
        };
        /** ToolCallStart */
        ToolCallStart: {
            /**
             * Parent Message Id
             * @default null
             */
            parent_message_id: string | null;
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Tool Call Id */
            tool_call_id: string;
            /** Tool Call Name */
            tool_call_name: string;
            /**
             * Type
             * @default TOOL_CALL_START
             * @constant
             */
            type: "TOOL_CALL_START";
        };
        /** ToolCallStarted */
        ToolCallStarted: {
            /** Args Json */
            args_json: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Tool Call Id */
            tool_call_id: string;
            /** Tool Name */
            tool_name: string;
            /** Trace Id */
            trace_id: string;
        };
        /** ToolResult */
        ToolResult: {
            /** Content */
            content: string;
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Role
             * @constant
             */
            role: "tool";
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Tool Call Id */
            tool_call_id: string;
            /**
             * Type
             * @default TOOL_RESULT
             * @constant
             */
            type: "TOOL_RESULT";
        };
        /** ToolResultReceived */
        ToolResultReceived: {
            /** Result */
            result: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Tool Call Id */
            tool_call_id: string;
            /** Trace Id */
            trace_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    streamRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreateRequest"];
            };
        };
        responses: {
            /** @description AG-UI event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStateView"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled run state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStateView"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listThreads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of threads */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadState"][];
                };
            };
        };
    };
    createThread: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadCreateRequest"];
            };
        };
        responses: {
            /** @description Created thread */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadState"];
                };
            };
        };
    };
    getThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thread state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadState"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
