/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agent/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's own memory items */
        get: operations["listMemory"];
        put?: never;
        /** Add a user-authored memory */
        post: operations["createMemory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/memory/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete one of the caller's memories */
        delete: operations["deleteMemory"];
        options?: never;
        head?: never;
        /** Soft-suppress / un-suppress one of the caller's memories (Phase B reject) */
        patch: operations["suppressMemory"];
        trace?: never;
    };
    "/agent/runs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open an SSE stream of AG-UI events for a run */
        post: operations["streamRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get run state */
        get: operations["getRun"];
        put?: never;
        post?: never;
        /** Cancel a run */
        delete: operations["cancelRun"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's own threads (newest-first, cursor) */
        get: operations["listThreads"];
        put?: never;
        /** Create a thread */
        post: operations["createThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a thread */
        get: operations["getThread"];
        put?: never;
        post?: never;
        /** Archive (soft-delete) a thread */
        delete: operations["archiveThread"];
        options?: never;
        head?: never;
        /** Rename a thread */
        patch: operations["renameThread"];
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List selectable models for the picker (name+tier only) */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BaseEvent
         * @description Common header for every AG-UI event.
         */
        BaseEvent: {
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            type: components["schemas"]["EventType"];
            $defs: {
                /**
                 * EventType
                 * @description The 17 AG-UI event-type discriminator strings.
                 * @enum {string}
                 */
                EventType: "RUN_STARTED" | "RUN_FINISHED" | "RUN_ERROR" | "STEP_STARTED" | "STEP_FINISHED" | "TEXT_MESSAGE_START" | "TEXT_MESSAGE_CONTENT" | "TEXT_MESSAGE_END" | "TOOL_CALL_START" | "TOOL_CALL_ARGS" | "TOOL_CALL_END" | "TOOL_RESULT" | "STATE_SNAPSHOT" | "STATE_DELTA" | "MESSAGES_SNAPSHOT" | "RAW" | "CUSTOM";
            };
        };
        /** Custom */
        Custom: {
            /** Name */
            name: string;
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default CUSTOM
             * @constant
             */
            type: "CUSTOM";
            /** Value */
            value: {
                [key: string]: unknown;
            };
        };
        /**
         * DomainEventBase
         * @description Common header for every internal domain event.
         */
        DomainEventBase: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * EventType
         * @description The 17 AG-UI event-type discriminator strings.
         * @enum {string}
         */
        EventType: "RUN_STARTED" | "RUN_FINISHED" | "RUN_ERROR" | "STEP_STARTED" | "STEP_FINISHED" | "TEXT_MESSAGE_START" | "TEXT_MESSAGE_CONTENT" | "TEXT_MESSAGE_END" | "TOOL_CALL_START" | "TOOL_CALL_ARGS" | "TOOL_CALL_END" | "TOOL_RESULT" | "STATE_SNAPSHOT" | "STATE_DELTA" | "MESSAGES_SNAPSHOT" | "RAW" | "CUSTOM";
        /**
         * HealthResponse
         * @description Response body of ``GET /healthz``.
         */
        HealthResponse: {
            /** Adapter Version */
            adapter_version: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** LLMMessageEnded */
        LLMMessageEnded: {
            /** Message Id */
            message_id: string;
            /**
             * Model
             * @default null
             */
            model: string | null;
            /**
             * Output Text
             * @default null
             */
            output_text: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Tokens In
             * @default null
             */
            tokens_in: number | null;
            /**
             * Tokens Out
             * @default null
             */
            tokens_out: number | null;
            /** Trace Id */
            trace_id: string;
        };
        /** LLMMessageStarted */
        LLMMessageStarted: {
            /**
             * Input Text
             * @default null
             */
            input_text: string | null;
            /** Message Id */
            message_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Trace Id */
            trace_id: string;
        };
        /** LLMTokenEmitted */
        LLMTokenEmitted: {
            /** Delta */
            delta: string;
            /** Message Id */
            message_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * MemoryCreateRequest
         * @description Body of ``POST /agent/memory`` — a user-added (manual) memory.
         *
         *     ``user_id`` is intentionally absent: the subject is the verified bearer
         *     identity, never client-supplied (cross-user-leak guard).
         */
        MemoryCreateRequest: {
            /** Content */
            content: string;
            /**
             * Key
             * @default null
             */
            key: string | null;
            /**
             * Salience
             * @default null
             */
            salience: number | null;
            /**
             * Type
             * @default semantic
             * @enum {string}
             */
            type: "semantic" | "episodic" | "procedural";
        };
        /**
         * MemoryItem
         * @description One stored memory item, surfaced to its owner in the panel.
         */
        MemoryItem: {
            /** Content */
            content: string;
            /** Key */
            key: string;
            /**
             * Salience
             * @default null
             */
            salience: number | null;
            /**
             * Type
             * @default null
             */
            type: ("semantic" | "episodic" | "procedural") | null;
        };
        /**
         * MemoryListResponse
         * @description Response body of ``GET /agent/memory`` — the caller's own items.
         */
        MemoryListResponse: {
            /** Items */
            items?: components["schemas"]["MemoryItem"][];
            $defs: {
                /**
                 * MemoryItem
                 * @description One stored memory item, surfaced to its owner in the panel.
                 */
                MemoryItem: {
                    /** Content */
                    content: string;
                    /** Key */
                    key: string;
                    /**
                     * Salience
                     * @default null
                     */
                    salience: number | null;
                    /**
                     * Type
                     * @default null
                     */
                    type: ("semantic" | "episodic" | "procedural") | null;
                };
            };
        };
        /**
         * MemoryRecalled
         * @description memory_layer_wiring plan Phase 3: the transparent-recall indicator's
         *     count (wire: Custom ``memory_recalled``). METADATA ONLY — carries the
         *     number of long-term memories the route node's recall returned, NEVER the
         *     content (the privacy invariant; the owner sees their content only in the
         *     memory panel). The frontend renders "recalled N memories" above the
         *     assistant turn; 0 renders nothing.
         *
         *     chat_persistence Phase B adds ``keys``: the stable identifiers of exactly
         *     the records injected this turn (in render order). Keys are identifiers, NOT
         *     payload content, so the privacy invariant still holds — the per-chat eval
         *     view joins them against the owner's own memory panel to render which
         *     memories were recalled (and offer a per-item reject/soft-suppress). Defaults
         *     to ``[]`` for backward compatibility (a count-only producer stays valid).
         */
        MemoryRecalled: {
            /** Count */
            count: number;
            /** Keys */
            keys?: string[];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * MemorySuppressRequest
         * @description Body of ``PATCH /agent/memory/{key}`` — soft-suppress / un-suppress one
         *     of the caller's own memories (chat-persistence Phase B, D5).
         *
         *     ``suppressed=True`` (reject) stops the memory being recalled/injected while
         *     RETAINING the row for audit; ``False`` un-suppresses (reversible). The
         *     subject is the verified bearer identity, never client-supplied.
         */
        MemorySuppressRequest: {
            /** Suppressed */
            suppressed: boolean;
        };
        /** MessagesSnapshot */
        MessagesSnapshot: {
            /** Messages */
            messages: {
                [key: string]: unknown;
            }[];
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default MESSAGES_SNAPSHOT
             * @constant
             */
            type: "MESSAGES_SNAPSHOT";
        };
        /**
         * ModelInfo
         * @description One selectable model on the wire — name + tier ONLY.
         *
         *     Pricing (cost_per_1k_*), ``litellm_id``, and context windows are runtime
         *     catalog internals and are deliberately NOT exposed to the client (the model
         *     name is non-secret; the cost table is not a client concern). The dropdown
         *     needs only the name to pin and the tier to group/label.
         */
        ModelInfo: {
            /** Name */
            name: string;
            /** Tier */
            tier: string;
        };
        /**
         * ModelsResponse
         * @description Response body of ``GET /models`` — the model picker's catalog.
         *
         *     ``default`` is the steady-state fast model name; ``models`` is the registry
         *     order (the router's first-match-per-tier contract). "Auto" is a UI sentinel,
         *     not a model — the client prepends it; the backend never lists it.
         */
        ModelsResponse: {
            /** Default */
            default: string;
            /** Models */
            models: components["schemas"]["ModelInfo"][];
            $defs: {
                /**
                 * ModelInfo
                 * @description One selectable model on the wire — name + tier ONLY.
                 *
                 *     Pricing (cost_per_1k_*), ``litellm_id``, and context windows are runtime
                 *     catalog internals and are deliberately NOT exposed to the client (the model
                 *     name is non-secret; the cost table is not a client concern). The dropdown
                 *     needs only the name to pin and the tier to group/label.
                 */
                ModelInfo: {
                    /** Name */
                    name: string;
                    /** Tier */
                    tier: string;
                };
            };
        };
        /** Raw */
        Raw: {
            /** Event */
            event: string;
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Source
             * @default null
             */
            source: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default RAW
             * @constant
             */
            type: "RAW";
        };
        /**
         * ReasoningSummarized
         * @description F10 Tier-2: one cheap-tier "why/how" recap per run (wire: Custom
         *     ``reasoning_summary``).
         */
        ReasoningSummarized: {
            /** Text */
            text: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * RunCreateRequest
         * @description Body of ``POST /agent/runs/stream`` and ``POST /agent/runs``.
         */
        RunCreateRequest: {
            /**
             * Agent Id
             * @default null
             */
            agent_id: string | null;
            /** Input */
            input: {
                [key: string]: unknown;
            };
            /** Thread Id */
            thread_id: string;
        };
        /** RunError */
        RunError: {
            /**
             * Code
             * @default null
             */
            code: string | null;
            /** Message */
            message: string;
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /** Run Id */
            run_id: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default RUN_ERROR
             * @constant
             */
            type: "RUN_ERROR";
        };
        /** RunFinished */
        RunFinished: {
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /** Run Id */
            run_id: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default RUN_FINISHED
             * @constant
             */
            type: "RUN_FINISHED";
        };
        /** RunFinishedDomain */
        RunFinishedDomain: {
            /**
             * Error
             * @default null
             */
            error: string | null;
            /** Run Id */
            run_id: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Trace Id */
            trace_id: string;
        };
        /** RunStarted */
        RunStarted: {
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /** Run Id */
            run_id: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default RUN_STARTED
             * @constant
             */
            type: "RUN_STARTED";
        };
        /** RunStartedDomain */
        RunStartedDomain: {
            /** Run Id */
            run_id: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * RunStateView
         * @description Response body of ``GET /agent/runs/{run_id}``.
         */
        RunStateView: {
            /** Completed At */
            completed_at: string | null;
            /** Run Id */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "completed" | "cancelled" | "errored";
            /** Thread Id */
            thread_id: string;
        };
        /** StateDelta */
        StateDelta: {
            /** Delta */
            delta: {
                [key: string]: unknown;
            }[];
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default STATE_DELTA
             * @constant
             */
            type: "STATE_DELTA";
        };
        /** StateMutated */
        StateMutated: {
            /**
             * Delta
             * @default null
             */
            delta: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Snapshot
             * @default null
             */
            snapshot: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Trace Id */
            trace_id: string;
        };
        /** StateSnapshot */
        StateSnapshot: {
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /** Snapshot */
            snapshot: {
                [key: string]: unknown;
            };
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default STATE_SNAPSHOT
             * @constant
             */
            type: "STATE_SNAPSHOT";
        };
        /** StepFinished */
        StepFinished: {
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /** Step Name */
            step_name: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default STEP_FINISHED
             * @constant
             */
            type: "STEP_FINISHED";
        };
        /** StepProgressed */
        StepProgressed: {
            /** Step Count */
            step_count: number;
            /** Step Name */
            step_name: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Trace Id */
            trace_id: string;
        };
        /** StepStarted */
        StepStarted: {
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /** Step Name */
            step_name: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default STEP_STARTED
             * @constant
             */
            type: "STEP_STARTED";
        };
        /**
         * TaskUnderstandingEditRequest
         * @description Edit payload for the soft-gate understanding card (Phase 4).
         *
         *     Wire shape consumed by the middleware edit endpoint — NEVER the
         *     components Pydantic type (M1: middleware never imports components/).
         *     Bounds mirror the components validation gates minus lexical grounding
         *     (``user_edited`` skips it: the human is the authority). ``trace_id``
         *     is echoed verbatim from the run (F-R7 — the browser never mints one).
         */
        TaskUnderstandingEditRequest: {
            /** Restated Intent */
            restated_intent: string;
            /** Success Conditions */
            success_conditions: string[];
            /** Trace Id */
            trace_id: string;
        };
        /**
         * TaskUnderstood
         * @description task_understanding plan Phase 3: plan-time intent restatement +
         *     success checklist for the soft-gate card (wire: Custom
         *     ``task_understanding``). ``source`` is the provenance tier
         *     (deterministic | generated | user_edited).
         */
        TaskUnderstood: {
            /** Confidence */
            confidence: number;
            /** Restated Intent */
            restated_intent: string;
            /** Source */
            source: string;
            /** Success Conditions */
            success_conditions: string[];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Trace Id */
            trace_id: string;
        };
        /** TextMessageContent */
        TextMessageContent: {
            /** Delta */
            delta: string;
            /** Message Id */
            message_id: string;
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default TEXT_MESSAGE_CONTENT
             * @constant
             */
            type: "TEXT_MESSAGE_CONTENT";
        };
        /** TextMessageEnd */
        TextMessageEnd: {
            /** Message Id */
            message_id: string;
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default TEXT_MESSAGE_END
             * @constant
             */
            type: "TEXT_MESSAGE_END";
        };
        /** TextMessageStart */
        TextMessageStart: {
            /** Message Id */
            message_id: string;
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Role
             * @constant
             */
            role: "assistant";
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Type
             * @default TEXT_MESSAGE_START
             * @constant
             */
            type: "TEXT_MESSAGE_START";
        };
        /**
         * ThreadCreateRequest
         * @description Body of ``POST /agent/threads``.
         *
         *     ``thread_id`` is optional: when the client mints the conversation id (so the
         *     durable thread row keys by the SAME id the agent/checkpointer uses for
         *     resume), it supplies it here. Absent → the store mints its own id (the
         *     legacy path). A provisional title still flows via ``metadata.first_message``
         *     (see ``derive_thread_title``).
         */
        ThreadCreateRequest: {
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Thread Id
             * @default null
             */
            thread_id: string | null;
            /** User Id */
            user_id: string;
        };
        /**
         * ThreadListResponse
         * @description Response body of ``GET /agent/threads`` — the caller's own threads,
         *     cursor-paginated.
         */
        ThreadListResponse: {
            /**
             * Next Cursor
             * @default null
             */
            next_cursor: string | null;
            /** Threads */
            threads?: components["schemas"]["ThreadState"][];
            $defs: {
                /**
                 * ThreadState
                 * @description Response body of ``GET /agent/threads/{thread_id}`` and items in the
                 *     ``GET /agent/threads`` list.
                 *
                 *     ``title`` is the sidebar label (Phase 3) — deterministic from the first
                 *     user message, user-renamable. ``archived_at`` is the soft-delete tombstone
                 *     (set on archive; list/get filter it out).
                 */
                ThreadState: {
                    /**
                     * Archived At
                     * @default null
                     */
                    archived_at: string | null;
                    /**
                     * Created At
                     * Format: date-time
                     */
                    created_at: string;
                    /** Messages */
                    messages?: {
                        [key: string]: unknown;
                    }[];
                    /** Thread Id */
                    thread_id: string;
                    /**
                     * Title
                     * @default New chat
                     */
                    title: string;
                    /**
                     * Updated At
                     * Format: date-time
                     */
                    updated_at: string;
                    /** User Id */
                    user_id: string;
                };
            };
        };
        /**
         * ThreadRenameRequest
         * @description Body of ``PATCH /agent/threads/{thread_id}`` — rename only.
         */
        ThreadRenameRequest: {
            /** Title */
            title: string;
        };
        /**
         * ThreadState
         * @description Response body of ``GET /agent/threads/{thread_id}`` and items in the
         *     ``GET /agent/threads`` list.
         *
         *     ``title`` is the sidebar label (Phase 3) — deterministic from the first
         *     user message, user-renamable. ``archived_at`` is the soft-delete tombstone
         *     (set on archive; list/get filter it out).
         */
        ThreadState: {
            /**
             * Archived At
             * @default null
             */
            archived_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Messages */
            messages?: {
                [key: string]: unknown;
            }[];
            /** Thread Id */
            thread_id: string;
            /**
             * Title
             * @default New chat
             */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** User Id */
            user_id: string;
        };
        /** ToolCallArgs */
        ToolCallArgs: {
            /** Delta */
            delta: string;
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Tool Call Id */
            tool_call_id: string;
            /**
             * Type
             * @default TOOL_CALL_ARGS
             * @constant
             */
            type: "TOOL_CALL_ARGS";
        };
        /** ToolCallEnd */
        ToolCallEnd: {
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Tool Call Id */
            tool_call_id: string;
            /**
             * Type
             * @default TOOL_CALL_END
             * @constant
             */
            type: "TOOL_CALL_END";
        };
        /** ToolCallEnded */
        ToolCallEnded: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Tool Call Id */
            tool_call_id: string;
            /** Trace Id */
            trace_id: string;
        };
        /** ToolCallStart */
        ToolCallStart: {
            /**
             * Parent Message Id
             * @default null
             */
            parent_message_id: string | null;
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Tool Call Id */
            tool_call_id: string;
            /** Tool Call Name */
            tool_call_name: string;
            /**
             * Type
             * @default TOOL_CALL_START
             * @constant
             */
            type: "TOOL_CALL_START";
        };
        /** ToolCallStarted */
        ToolCallStarted: {
            /** Args Json */
            args_json: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Tool Call Id */
            tool_call_id: string;
            /** Tool Name */
            tool_name: string;
            /** Trace Id */
            trace_id: string;
        };
        /** ToolResult */
        ToolResult: {
            /** Content */
            content: string;
            /**
             * Raw Event
             * @default null
             */
            raw_event: {
                [key: string]: unknown;
            } | null;
            /**
             * Role
             * @constant
             */
            role: "tool";
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Tool Call Id */
            tool_call_id: string;
            /**
             * Type
             * @default TOOL_RESULT
             * @constant
             */
            type: "TOOL_RESULT";
        };
        /** ToolResultReceived */
        ToolResultReceived: {
            /** Result */
            result: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Tool Call Id */
            tool_call_id: string;
            /** Trace Id */
            trace_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listMemory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's memory items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Memory service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createMemory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryCreateRequest"];
            };
        };
        responses: {
            /** @description Created memory */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryItem"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Memory service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Memory not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    suppressMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemorySuppressRequest"];
            };
        };
        responses: {
            /** @description Suppression flag updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Memory not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    streamRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreateRequest"];
            };
        };
        responses: {
            /** @description AG-UI event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStateView"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled run state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStateView"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listThreads: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's threads */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createThread: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadCreateRequest"];
            };
        };
        responses: {
            /** @description Created thread */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadState"];
                };
            };
        };
    };
    getThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thread state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadState"];
                };
            };
        };
    };
    archiveThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thread not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    renameThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadRenameRequest"];
            };
        };
        responses: {
            /** @description Renamed thread */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadState"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thread not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The active registry's model catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
